package com.owl.domain.model

enum class Topic(val displayName: String) {
    ANDROID("Android"),
    KOTLIN("Kotlin"),
    PATTERNS("Design Patterns"),
    ARCHITECTURE("Architecture"),
    UI_AND_ANIMATIONS("UI & Animations"),
    PERFORMANCE("Performance Optimization"),
    MULTITHREADING("Multithreading"),
    DATABASE("Database & Storage"),
    NETWORKING("Networking"),
    SECURITY("Security"),
    TESTING("Testing"),
    DEPENDENCY_INJECTION("Dependency Injection"),
    REACTIVE_PROGRAMMING("Reactive Programming"),
    KOTLIN_COROUTINES("Kotlin Coroutines"),
    KOTLIN_FLOW("Kotlin Flow"),
    ANDROID_JETPACK("Android Jetpack"),
    COMPOSE("Jetpack Compose"),
    DEBUGGING("Debugging & Profiling"),
    BUILD_TOOLS("Build Tools & Gradle"),
    MEMORY_MANAGEMENT("Memory Management"),
    CUSTOM_VIEWS("Custom Views"),
    NOTIFICATIONS("Notifications"),
    SERVICES("Services & Background Work"),
    BROADCASTS("Broadcasts"),
    APP_LIFECYCLE("App Lifecycle"),
    FRAGMENTS("Fragments"),
    ACTIVITIES("Activities"),
    VIEW_MODEL("ViewModel"),
    LIVE_DATA("LiveData"),
    WORK_MANAGER("WorkManager"),
    ROOM_DB("Room Database"),
    DATASTORE("DataStore"),
    PAGING("Paging Library"),
    NAVIGATION("Navigation Component"),
    HILT("Hilt"),
    DAGGER("Dagger"),
    KOIN("Koin"),
    UNIT_TESTING("Unit Testing"),
    UI_TESTING("UI Testing"),
    CI_CD("CI/CD for Android"),
    APP_DISTRIBUTION("App Distribution"),
    PLAY_STORE("Play Store Publishing"),
    MATERIAL_DESIGN("Material Design"),
    ACCESSIBILITY("Accessibility"),
    LOCALIZATION("Localization"),
    DEEPLINKS("Deep Links & App Links"),
    PERMISSIONS("Permissions"),
    FILE_STORAGE("File Storage"),
    CAMERA_API("Camera API"),
    LOCATION_API("Location API"),
    SENSORS("Sensors"),
    BLUETOOTH("Bluetooth"),
    NFC("NFC"),
    BIOMETRICS("Biometrics"),
    PAYMENTS("In-app Purchases & Payments"),
    ADS("Advertising & Monetization"),
    ANALYTICS("Analytics"),
    CRASHLYTICS("Crashlytics"),
    FIREBASE("Firebase"),
    WEAR_OS("Wear OS"),
    TV("Android TV"),
    AUTO("Android Auto"),
    THINGS("Android Things"),
    KMM("Kotlin Multiplatform Mobile"),
    FLUTTER_COMPARISON("Flutter Comparison"),
    REACT_NATIVE_COMPARISON("React Native Comparison"),
    CLEAN_ARCHITECTURE("Clean Architecture"),
    MVP("MVP Pattern"),
    MVVM("MVVM Pattern"),
    MVI("MVI Pattern"),
    VIPER("VIPER Pattern"),
    SOLID("SOLID Principles"),
    KISS_DRY_YAGNI("KISS, DRY, YAGNI"),
    DATA_STRUCTURES("Data Structures"),
    ALGORITHMS("Algorithms"),
    SYSTEM_DESIGN("System Design"),
    APP_ARCHITECTURE("App Architecture"),
    CODE_STYLE("Code Style & Best Practices"),
    VERSION_CONTROL("Version Control (Git)"),
    CODE_REVIEW("Code Review Practices"),
    AGILE_DEVELOPMENT("Agile Development"),
    SOFT_SKILLS("Soft Skills"),
    SYSTEM_INTERVIEW("System Design Interview")
}

enum class Difficulty {
    JUNIOR, MIDDLE, SENIOR
}

data class InterviewSettings(
    val topic: Topic,
    val difficulty: Difficulty,
    val questionCount: Int
)