package com.owl.data.service

import android.util.Log
import com.google.ai.client.generativeai.GenerativeModel
import com.google.ai.client.generativeai.type.generationConfig
import com.owl.data.network.model.EvaluationDto
import com.owl.data.network.model.NetworkQuestionDto
import com.owl.domain.common.Resource
import com.owl.domain.model.AppLanguage
import com.owl.domain.model.InterviewSettings
import com.owl.domain.model.Question
import com.owl.domain.port.service.AiInterviewerService
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import kotlin.collections.map

class AiInterviewerServiceImpl(
    private val apiKey: String
) : AiInterviewerService {

    private val generativeModel by lazy {
        GenerativeModel(
            modelName = "gemini-2.5-flash",
            apiKey = apiKey,
            generationConfig = generationConfig {
                responseMimeType = "application/json"
            }
        )
    }

    private val jsonParser = Json {
        ignoreUnknownKeys = true
        isLenient = true
    }

    override suspend fun generateQuestions(settings: InterviewSettings, language: AppLanguage): Resource<List<Question>> =
        withContext(Dispatchers.IO) {
            try {
                val languageInstruction = if (language == AppLanguage.RUSSIAN) {
                    "Conduct the interview in Russian language. ALL QUESTIONS MUST BE IN RUSSIAN."
                } else {
                    "Conduct the interview in English language."
                }

                val prompt = """
                You are a strict Senior Android Developer conducting a technical interview.
                $languageInstruction
                Generate ${settings.questionCount} interview questions about "${settings.topic.displayName}".
                Difficulty level: ${settings.difficulty.name}.
                
                Return the result ONLY as a JSON Array with this exact schema:
                [
                  {
                    "text": "Question text here",
                    "topic": "${settings.topic.name}",
                    "difficulty": "${settings.difficulty.name}"
                  }
                ]
                Do not add any markdown formatting. Just raw JSON.
            """.trimIndent()

                val response = generativeModel.generateContent(prompt)
                val responseText = response.text ?: return@withContext Resource.Error("Empty response from AI")

                val cleanJson = responseText
                    .replace("```json", "")
                    .replace("```", "")
                    .trim()

                val dtos = jsonParser.decodeFromString<List<NetworkQuestionDto>>(cleanJson)

                val questions = dtos.map { dto ->
                    Question(
                        id = java.util.UUID.randomUUID().toString(),
                        text = dto.text,
                        topic = settings.topic,
                        difficulty = settings.difficulty
                    )
                }

                Resource.Success(questions)
            } catch (e: Exception) {
                Log.e("GeminiResp", "Error parsing JSON", e)
                Resource.Error("Failed to generate questions. Please try again.")
            }
        }

    override suspend fun evaluateAnswer(question: Question, answer: String, language: AppLanguage): Resource<Question> =
        withContext(Dispatchers.IO) {
            try {
                val languageInstruction = if (language == AppLanguage.RUSSIAN) {
                    "Provide feedback and ideal answer in Russian language."
                } else {
                    "Provide feedback and ideal answer in English language."
                }

                val prompt = """
                    You are a Senior Android Interviewer.
                    $languageInstruction
                    Question: "${question.text}"
                    Topic: ${question.topic.displayName}
                    User Answer: "$answer"
                    
                    IMPORTANT: The 'User Answer' was generated by a poor-quality Speech-to-Text engine. 
                    It may contain severe grammatical errors, missing words, or phonetically misspelled technical terms (e.g., translating IT slang into random Russian words). 
                    Focus ONLY on the semantic meaning and technical correctness of the answer, ignoring typos and weird phrasing.
                    
                    Evaluate the answer concisely. 
                    If the answer is empty or nonsense, give rating 1.
                    
                    Return ONLY JSON:
                    {
                      "rating": (integer 1-10),
                      "feedback": "Short constructive feedback (max 2 sentences)",
                      "idealAnswer": "A concise correct answer (max 2 sentences)"
                    }
                """.trimIndent()

                val response = generativeModel.generateContent(prompt)
                val responseText = response.text ?: return@withContext Resource.Error("Empty response from AI")
                val evaluation = jsonParser.decodeFromString<EvaluationDto>(responseText)

                val ratedQuestion = question.copy(
                    userAnswerText = answer,
                    aiFeedback = evaluation.feedback + "\n\nIdeal: " + evaluation.idealAnswer,
                    rating = evaluation.rating,
                    isCompleted = true
                )

                Resource.Success(ratedQuestion)
            } catch (e: Exception) {
                Log.e("GeminiResp", "Error evaluating answer", e)
                Resource.Error("Failed to evaluate answer. Please try again.")
            }
        }
}